import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 bg-blue-950 text-white flex justify-between">
          <Link href='/products' >Productos </Link>
          <Link href='/cart' >Carrito </Link>
        </header>
        <main className="p-4">
          {children}
        </main>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
